# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 773b52641ce62d0fb4ee08d038327bec8897d8c83a4700274cbaf9880e8ac229fe4b03ad5b630808c5fe09caf12157c87501692896a4d108b2c1c0d8dfef7fbf

test:
  secret_key_base: 350acfe45392ac51de55d51dbcafb0ab785242832f6ec328531a08b0922482239d103537be9595ab05e8a85262485acc4c0eeeefc016fc46e383ee044a208bc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
